### ISSUE TITLE
schema error

### ISSUE THREAD

**Issue by porjo** [mchangrh/sb-openapi-source#4]
I've tried using a couple of code generators for Go but running into errors. For example, using https://openapi-generator.tech/ I get this error:

```
$ java -jar openapi-generator-cli.jar generate -g go -i openapi.yaml -o sponsorblock
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors: 
	-attribute paths.'/lockReason'(get).parameters.[category].schemas.items is missing

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:604)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```
I've also tried https://github.com/deepmap/oapi-codegen and got a similar error. I was able to make the error stop with this change but not sure if that's correct:

```diff
1279,1287c1279,1289
<             enum:
<               - sponsor
<               - selfpromo
<               - interaction
<               - intro
<               - outro
<               - preview
<               - music_offtopic
<               - poi_highlight
---
>             items:
>               type: string
>               enum:
>                 - sponsor
>                 - selfpromo
>                 - interaction
>                 - intro
>                 - outro
>                 - preview
>                 - music_offtopic
>                 - poi_highlight
```

**Comment by mchangrh** [comment]
sorry to leave you hanging, I must've dreamed up addressing it.

It was twofold, `minItems` being 0 and the items: type not being defined

**Comment by porjo** [comment]
Thanks 👍
